//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The OpDev Maintainers.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisconnectedFriendlyApp) DeepCopyInto(out *DisconnectedFriendlyApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisconnectedFriendlyApp.
func (in *DisconnectedFriendlyApp) DeepCopy() *DisconnectedFriendlyApp {
	if in == nil {
		return nil
	}
	out := new(DisconnectedFriendlyApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisconnectedFriendlyApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisconnectedFriendlyAppList) DeepCopyInto(out *DisconnectedFriendlyAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DisconnectedFriendlyApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisconnectedFriendlyAppList.
func (in *DisconnectedFriendlyAppList) DeepCopy() *DisconnectedFriendlyAppList {
	if in == nil {
		return nil
	}
	out := new(DisconnectedFriendlyAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisconnectedFriendlyAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisconnectedFriendlyAppSpec) DeepCopyInto(out *DisconnectedFriendlyAppSpec) {
	*out = *in
	if in.BusyBoxReplicas != nil {
		in, out := &in.BusyBoxReplicas, &out.BusyBoxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.SleeperReplicas != nil {
		in, out := &in.SleeperReplicas, &out.SleeperReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisconnectedFriendlyAppSpec.
func (in *DisconnectedFriendlyAppSpec) DeepCopy() *DisconnectedFriendlyAppSpec {
	if in == nil {
		return nil
	}
	out := new(DisconnectedFriendlyAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisconnectedFriendlyAppStatus) DeepCopyInto(out *DisconnectedFriendlyAppStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisconnectedFriendlyAppStatus.
func (in *DisconnectedFriendlyAppStatus) DeepCopy() *DisconnectedFriendlyAppStatus {
	if in == nil {
		return nil
	}
	out := new(DisconnectedFriendlyAppStatus)
	in.DeepCopyInto(out)
	return out
}
